package com.cars.halamotor.functions;

import android.content.Context;

import com.cars.halamotor.R;
import com.cars.halamotor.model.CarModel;

import java.util.ArrayList;

public class FillCarModel {

    public static ArrayList<CarModel> fillCarMakeArrayL(ArrayList<CarModel> carModelArrayList, Context context, String carMake) {
        carModelArrayList = new ArrayList<CarModel>();

        if (carMake.equals(context.getString(R.string.hyundai)))
        {
            carModelArrayList.add(new CarModel(context.getString(R.string.h_1_starex),context.getString(R.string.h_1_starex_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.i_10),context.getString(R.string.i_10_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.i_20),context.getString(R.string.i_20_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.i_30),context.getString(R.string.i_30_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.i_40),context.getString(R.string.i_40_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.atos),context.getString(R.string.atos_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.azera),context.getString(R.string.azera_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.accent),context.getString(R.string.accent_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.h_100),context.getString(R.string.h_100_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.excel),context.getString(R.string.excel_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.elantra),context.getString(R.string.elantra_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.avante),context.getString(R.string.avante_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.equus),context.getString(R.string.equus_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.ioniq),context.getString(R.string.ioniq_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.porter),context.getString(R.string.porter_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.pony),context.getString(R.string.pony_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.trajet),context.getString(R.string.trajet_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.tuscani),context.getString(R.string.tuscani_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.terracan),context.getString(R.string.terracan_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.tiburon),context.getString(R.string.tiburon_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.galloper),context.getString(R.string.galloper_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.getz),context.getString(R.string.getz_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.genesis),context.getString(R.string.genesis_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.genesis_coupe),context.getString(R.string.genesis_coupe_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.santamo),context.getString(R.string.santamo_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.stellar),context.getString(R.string.stellar_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.scoupe),context.getString(R.string.scoupe_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.santa_fe),context.getString(R.string.santa_fe_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.centennial),context.getString(R.string.centennial_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.sonata),context.getString(R.string.sonata_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.veloster),context.getString(R.string.veloster_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.veracruz),context.getString(R.string.veracruz_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.verna),context.getString(R.string.verna_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.creta),context.getString(R.string.creta_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.coupe),context.getString(R.string.coupe_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.matrix),context.getString(R.string.matrix_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.mighty),context.getString(R.string.mighty_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kona),context.getString(R.string.kona_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.eon),context.getString(R.string.eon_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.palisade),context.getString(R.string.palisade_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.click),context.getString(R.string.click_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.entourage),context.getString(R.string.entourage_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.county),context.getString(R.string.county_s)));
        }

        if (carMake.equals(context.getString(R.string.toyota)))
        {
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_4runner),context.getString(R.string.toyota_4runner_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_c_hr),context.getString(R.string.toyota_c_hr_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_mr2),context.getString(R.string.toyota_mr2_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_iq),context.getString(R.string.toyota_iq_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_avalon),context.getString(R.string.toyota_avalon_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_avanza),context.getString(R.string.toyota_avanza_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_avensis),context.getString(R.string.toyota_avensis_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_alphard),context.getString(R.string.toyota_alphard_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_allex),context.getString(R.string.toyota_allex_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_opa),context.getString(R.string.toyota_opa_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_auris),context.getString(R.string.toyota_auris_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_echo),context.getString(R.string.toyota_echo_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_innova),context.getString(R.string.toyota_innova_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_aristo),context.getString(R.string.toyota_aristo_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_fj_cruiser),context.getString(R.string.toyota_fj_cruiser_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_mark_x),context.getString(R.string.toyota_mark_x_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_altezza),context.getString(R.string.toyota_altezza_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_allion),context.getString(R.string.toyota_allion_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_urban_cruiser),context.getString(R.string.toyota_urban_cruiser_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_orgin),context.getString(R.string.toyota_orgin_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_aurion),context.getString(R.string.toyota_aurion_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_ipsum),context.getString(R.string.toyota_ipsum_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_aygo),context.getString(R.string.toyota_aygo_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_passo),context.getString(R.string.toyota_passo_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_paseo),context.getString(R.string.toyota_paseo_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_prado),context.getString(R.string.toyota_prado_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_probox),context.getString(R.string.toyota_probox_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_progres),context.getString(R.string.toyota_progres_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_pronard),context.getString(R.string.toyota_pronard_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_previa),context.getString(R.string.toyota_previa_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_premio),context.getString(R.string.toyota_premio_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_prius),context.getString(R.string.toyota_prius_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_prius_c),context.getString(R.string.toyota_prius_c_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_blade),context.getString(R.string.toyota_blade_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_blizzard),context.getString(R.string.toyota_blizzard_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_porte),context.getString(R.string.toyota_porte_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_bb),context.getString(R.string.toyota_bb_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_picnic),context.getString(R.string.toyota_picnic_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_tacoma),context.getString(R.string.toyota_tacoma_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_townace),context.getString(R.string.toyota_townace_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_chaser),context.getString(R.string.toyota_chaser_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_tundra),context.getString(R.string.toyota_tundra_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_tercel),context.getString(R.string.toyota_tercel_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_grand_hiace),context.getString(R.string.toyota_grand_hiace_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_gt_86),context.getString(R.string.toyota_gt_86_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_duet),context.getString(R.string.toyota_duet_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_dyna),context.getString(R.string.toyota_dyna_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_rav_4),context.getString(R.string.toyota_rav_4_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_ractis),context.getString(R.string.toyota_ractis_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_raum),context.getString(R.string.toyota_raum_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_rush),context.getString(R.string.toyota_rush_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_regius),context.getString(R.string.toyota_regius_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_zelas),context.getString(R.string.toyota_zelas_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_sparky),context.getString(R.string.toyota_sparky_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_sprinter),context.getString(R.string.toyota_sprinter_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_starlet),context.getString(R.string.toyota_starlet_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_succeed),context.getString(R.string.toyota_succeed_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_scepter),context.getString(R.string.toyota_scepter_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_supra),context.getString(R.string.toyota_supra_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_soarer),context.getString(R.string.toyota_soarer_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_soluna),context.getString(R.string.toyota_soluna_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_sera),context.getString(R.string.toyota_sera_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_sequoia),context.getString(R.string.toyota_sequoia_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_celsior),context.getString(R.string.toyota_celsior_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_sequoia),context.getString(R.string.toyota_sequoia_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_celsior),context.getString(R.string.toyota_celsior_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_celica),context.getString(R.string.toyota_celica_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_sienta),context.getString(R.string.toyota_sienta_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_scion),context.getString(R.string.toyota_scion_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_sienna),context.getString(R.string.toyota_sienna_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_land_cruiser_pickup),context.getString(R.string.toyota_land_cruiser_pickup_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_gaia),context.getString(R.string.toyota_gaia_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_granvia),context.getString(R.string.toyota_granvia_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_vellfire),context.getString(R.string.toyota_vellfire_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_venza),context.getString(R.string.toyota_venza_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_fun_cargo),context.getString(R.string.toyota_fun_cargo_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_fortuner),context.getString(R.string.toyota_fortuner_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_voxy),context.getString(R.string.toyota_voxy_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_voltz),context.getString(R.string.toyota_voltz_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_verso),context.getString(R.string.toyota_verso_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_carina),context.getString(R.string.toyota_carina_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_cavalier),context.getString(R.string.toyota_cavalier_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_caldina),context.getString(R.string.toyota_caldina_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_camry),context.getString(R.string.toyota_camry_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_crown),context.getString(R.string.toyota_crown_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_cressida),context.getString(R.string.toyota_cressida_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_corolla),context.getString(R.string.toyota_corolla_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_Corona),context.getString(R.string.toyota_Corona_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_coaster),context.getString(R.string.toyota_coaster_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_land_cruiser),context.getString(R.string.toyota_land_cruiser_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_land_cruiser_j70),context.getString(R.string.toyota_land_cruiser_j70_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_liteAce),context.getString(R.string.toyota_liteAce_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_matrix),context.getString(R.string.toyota_matrix_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_mark_2),context.getString(R.string.toyota_mark_2_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_master_ace),context.getString(R.string.toyota_master_ace_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_mega_cruiser),context.getString(R.string.toyota_mega_cruiser_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_harrier),context.getString(R.string.toyota_harrier_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_hiace),context.getString(R.string.toyota_hiace_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_highlander),context.getString(R.string.toyota_highlander_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_hilux),context.getString(R.string.toyota_hilux_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_wish),context.getString(R.string.toyota_wish_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_will),context.getString(R.string.toyota_will_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_windom),context.getString(R.string.toyota_windom_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_yaris),context.getString(R.string.toyota_yaris_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_2000_gt),context.getString(R.string.toyota_2000_gt_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_ai_300),context.getString(R.string.toyota_ai_300_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_will),context.getString(R.string.toyota_will_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_axio),context.getString(R.string.toyota_axio_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_celstar),context.getString(R.string.toyota_celstar_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_corolla),context.getString(R.string.toyota_corolla_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_fielder),context.getString(R.string.toyota_fielder_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_noah),context.getString(R.string.toyota_noah_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_rumion),context.getString(R.string.toyota_rumion_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_runx),context.getString(R.string.toyota_runx_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_solara),context.getString(R.string.toyota_solara_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_sprinter_carib),context.getString(R.string.toyota_sprinter_carib_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_vanguard),context.getString(R.string.toyota_vanguard_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.toyota_verossa),context.getString(R.string.toyota_verossa_s)));

        }

        if (carMake.equals(context.getString(R.string.kia)))
        {
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_asia),context.getString(R.string.kia_asia_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_avila),context.getString(R.string.kia_avila_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_optima),context.getString(R.string.kia_optima_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_opirus),context.getString(R.string.kia_opirus_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_elan),context.getString(R.string.kia_elan_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_pride),context.getString(R.string.kia_pride_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_borrego),context.getString(R.string.kia_borrego_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_bongo),context.getString(R.string.kia_bongo_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_besta),context.getString(R.string.kia_besta_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_picanto),context.getString(R.string.kia_picanto_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_granbird),context.getString(R.string.kia_granbird_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_joice),context.getString(R.string.kia_joice_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_retona),context.getString(R.string.kia_retona_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_rio),context.getString(R.string.kia_rio_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_sportage),context.getString(R.string.kia_sportage_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_spectra),context.getString(R.string.kia_spectra_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_sorento),context.getString(R.string.kia_sorento_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_soul),context.getString(R.string.kia_soul_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_cerato),context.getString(R.string.kia_cerato_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_cerato_koup),context.getString(R.string.kia_cerato_koup_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_sephia),context.getString(R.string.kia_sephia_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_sienna),context.getString(R.string.kia_sienna_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_shuma),context.getString(R.string.kia_shuma_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_forte),context.getString(R.string.kia_forte_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_venga),context.getString(R.string.kia_venga_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_captital),context.getString(R.string.kia_captital_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_cadenza),context.getString(R.string.kia_cadenza_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_carens),context.getString(R.string.kia_carens_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_carnival),context.getString(R.string.kia_carnival_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_clarus),context.getString(R.string.kia_clarus_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_quoris),context.getString(R.string.kia_quoris_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_cosmos),context.getString(R.string.kia_cosmos_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_concorde),context.getString(R.string.kia_concorde_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_magnetis),context.getString(R.string.kia_magnetis_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_mohave),context.getString(R.string.kia_mohave_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_niro),context.getString(R.string.kia_niro_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_ray),context.getString(R.string.kia_ray_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_telluride),context.getString(R.string.kia_telluride_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_stinger),context.getString(R.string.kia_stinger_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_creed),context.getString(R.string.kia_creed_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_stonic),context.getString(R.string.kia_stonic_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_sedona),context.getString(R.string.kia_sedona_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_lotze),context.getString(R.string.kia_lotze_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.kia_pegas),context.getString(R.string.kia_pegas_s)));
        }
        if (carMake.equals(context.getString(R.string.audi)))
        {
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a),context.getString(R.string.audi_a_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a1),context.getString(R.string.audi_a1_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a2),context.getString(R.string.audi_a2_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a3),context.getString(R.string.audi_a3_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a4),context.getString(R.string.audi_a4_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a5),context.getString(R.string.audi_a5_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a6),context.getString(R.string.audi_a6_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a7),context.getString(R.string.audi_a7_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a8),context.getString(R.string.audi_a8_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_a9),context.getString(R.string.audi_a9_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_q),context.getString(R.string.audi_q_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_q3),context.getString(R.string.audi_q3_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_q5),context.getString(R.string.audi_q5_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_q7),context.getString(R.string.audi_q7_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_r),context.getString(R.string.audi_r_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_r8),context.getString(R.string.audi_r8_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_rs1),context.getString(R.string.audi_rs1_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_rs2),context.getString(R.string.audi_rs2_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_rs3),context.getString(R.string.audi_rs3_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_rs4),context.getString(R.string.audi_rs4_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_rs5),context.getString(R.string.audi_rs5_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_rs6),context.getString(R.string.audi_rs6_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_s_),context.getString(R.string.audi_s__s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_s1),context.getString(R.string.audi_s1_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_s3),context.getString(R.string.audi_s3_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_s4),context.getString(R.string.audi_s4_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_s5),context.getString(R.string.audi_s5_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_s6),context.getString(R.string.audi_s6_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_s7),context.getString(R.string.audi_s7_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_s8),context.getString(R.string.audi_s8_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_50),context.getString(R.string.audi_50_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_60),context.getString(R.string.audi_60_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_80),context.getString(R.string.audi_80_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_90),context.getString(R.string.audi_90_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_100),context.getString(R.string.audi_100_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_200),context.getString(R.string.audi_200_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_tt),context.getString(R.string.audi_tt_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_v8),context.getString(R.string.audi_v8_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_cabriolet),context.getString(R.string.audi_cabriolet_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_quattro),context.getString(R.string.audi_quattro_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_coupe),context.getString(R.string.audi_coupe_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_e_tron),context.getString(R.string.audi_e_tron_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_tt_rs),context.getString(R.string.audi_tt_rs_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_tts),context.getString(R.string.audi_tts_s)));
            carModelArrayList.add(new CarModel(context.getString(R.string.audi_other),context.getString(R.string.audi_other_s)));


        }

            return carModelArrayList;
    }

}
